name: Build and Publish MobaXterm Chocolatey Package

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
    
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    
      - name: Verify Chocolatey installation
        run: choco -v
    
      - name: Pack Chocolatey package
        working-directory: mobaxterm
        run: choco pack
    
      - name: Test install package locally
        working-directory: mobaxterm
        run: |
          $pkg = Get-ChildItem *.nupkg | Select-Object -First 1
          # choco install $pkg.FullName -y --debug --verbose --source $pkg.DirectoryName
          choco install mobaxterm --version="26.3.0" --source="D:\a\chocolatey-packages\chocolatey-packages\mobaxterm"
    
      - name: Test uninstall package
        run: choco uninstall mobaxterm -y
    
      - name: Push package to Chocolatey
        if: success()
        working-directory: mobaxterm
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          $pkg = Get-ChildItem *.nupkg | Select-Object -First 1
          choco push $pkg.FullName --source https://push.chocolatey.org/ --api-key $env:CHOCO_API_KEY
